### ISSUE TITLE
Documentation Update for error "2012"

### ISSUE THREAD

**Issue by gavinjhunter** [Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams#3]
The same error within https://github.com/Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams/wiki/Known-Issues for "Wave" can also occur for the other 2 flows (Feedback and "Talk to a Real Person". 

The solution is to open the topic, delete and recreate the last step, then save the topic. Updating the known issues to include this would be awesome.

**Comment by Erithano** [comment]
@gavinjhunter - Thanks for noticing and sharing the workaround! 
Confirming from our side that we've seen this, and your suggested fix is great.

Will definitely update known issues to include this!
![Thank you gavinjhunter](https://user-images.githubusercontent.com/65014935/150992424-dce5061a-3462-4572-8510-d877b4068b94.gif)

**Comment by Erithano** [comment]
Known issues have been updated! Thanks again @gavinjhunter 
Closing this issue 🙂👍
