### ISSUE TITLE
italian

### ISSUE THREAD

**Issue by 23ale10** [Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams#5]
Hello,
when I import the zip into flow it doesn't load it and gives error on two missing dependencies.
with the zip in English it works correctly

**Comment by Erithano** [comment]
Ciao @23ale10!

Sorry to hear that. The Italian version was just recently published. Please share a screenshot and we'll make sure to follow up on it 👍

**Update:** We were able to reproduce the error and will work to fix it asap!
![image](https://user-images.githubusercontent.com/65014935/178481801-005adca0-c7ba-4406-884b-950657c09560.png)

**Comment by Erithano** [comment]
**@23ale10 - Please try the new updated Italian version 1.0.0.9 😀✔️**

We have confirmed that it should solve your issue with importing. Thanks so much! / Grazie!

Marking as completed ✔️

**Comment by Erithano** [comment]
Solved as of July 12th 👍🙂
