### ISSUE TITLE
Facing permission issue with Timon in MS Teams

### ISSUE THREAD

**Issue by changelahiren** [Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams#6]
Hi Team,
I am getting below permission issue with Timon. Can some please help me with the same? Please refer below screenshot for the same.

![image](https://user-images.githubusercontent.com/94886023/207608780-08b72932-c330-44d6-9f8f-58d85ae70217.png)

**Comment by changelahiren** [comment]
The above admin approval has been provided. Now, I am getting below permission issue. Can some please help me with the same?

![image](https://user-images.githubusercontent.com/94886023/207607624-2f049f8b-f95c-422a-9b32-d7998c77b282.png)

**Comment by Erithano** [comment]
Hey @changelahiren,

I'll try to help 😊.

I see two options here:

Option 1 
- **This is expected** **_if_** you just uploaded the Teams app "Timon Empty Manifest EN" and started chatting.

Solution: You need to import Timon to your tenant, as per the [Deployment Guide](https://github.com/Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams/wiki/Deployment-Guide), so you can get your own bot ID.
In the Developer portal app in Teams, you can then edit "Timon Empty Manifest EN" and replace the existing bot ID with your own.

Option 2

If you followed the Deployment guide, make sure you have a policy that allows you to interact with custom apps.
In Teams Admin Center, make sure the following is on:
![image](https://user-images.githubusercontent.com/65014935/208337524-5fea1cac-92a4-4ae8-b76e-884e3180a333.png)
This is needed to interact with the bot in your custom app.

Hope this helps 👍
